name: Minify JavaScript

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install Terser
              run: npm install terser -g

            - name: Minify JS
              run: terser src/minifier.js -o dist/minifier.min.js

            - name: Commit and Push
              run: |
                  git config --local user.name "GitHub Actions"
                  git config --local user.email "actions@github.com"
                  git add dist/minifier.min.js
                  git commit -m "Minify JavaScript"
                  git push origin main
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
